repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use the latest version from GitHub releases
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=250"]  # 50MB limit (adjust as needed)
      - id: check-case-conflict
      - id: check-merge-conflict
